# Generated by Django 4.1.7 on 2023-03-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_finch_finches'),
    ]

    operations = [
        migrations.AddField(
            model_name='finches',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
